### ISSUE TITLE
Composer prevents install

### ISSUE THREAD

**Issue by JasonElkin** [nul800sebastiaan/Cultiv.Hangfire#11]
While having some fun with with https://github.com/JasonElkin/Hangfire-Umbraco-Example I noticed that the composer [throws an exception when there's no connection string](https://github.com/nul800sebastiaan/Cultiv.Hangfire/blob/6f16ad9fa9566066b26c0a7d51fcff3f3c384716/Cultiv.Hangfire/HangfireComposer.cs#L19-L22).

A site that hasn't run the installer yet won't have a connection string. If you install Cultiv.Hangfire on a brand spanking new, never before run, Umbraco repo, you won't be able to start the site.

Previously composers had a RuntimeLevel attribute to prevent this, but that's gone in v9+ and I'm not yet sure what the answer is.

**Comment by nul800sebastiaan** [comment]
@JasonElkin I had a look and the only thing I can think of right now is if the connection string is not found, we just skip the whole Hangfire setup. That means that Umbraco's install will run, but you'd need to stop/start the site for the Hangfire install to happen next. I think it's an acceptable trade-off for now. It's released in v2.0.1 now (compatible with v10, not v9).
