### ISSUE TITLE
EF Migrations won't run

### ISSUE THREAD

**Issue by Sibren** [nul800sebastiaan/Cultiv.Hangfire#17]
Hi,

When I try to add a migration (Add-Migration **name** from package manager console) from EF Core on my Umbraco 10-project, I get the following error:

> An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: JobStorage.Current property value has not been initialized. You must set it before using Hangfire Client or Server API.

Do you have any idea what it could be?

Umbraco 10.2.1
Cultiv.Hangfire 2.3.0

**Comment by nul800sebastiaan** [comment]
Sorry, absolutely no idea. I used EF for the last time 15 years ago 😅 

I'm assuming EF is starting before Hangfire maybe.. but really, no clue.

**Comment by nul800sebastiaan** [comment]
I'll close this one for now and will encourage you to use the official EF support in Umbraco 12, hopefully that will work better with this package.

https://docs.umbraco.com/umbraco-cms/tutorials/getting-started-with-entity-framework-core
