### ISSUE TITLE
Type load exception with Hangfire 1.8.1.0

### ISSUE THREAD

**Issue by jrunestone** [nul800sebastiaan/Cultiv.Hangfire#19]
Hi Sebastiaan,

Updated the hangfire nuget to 1.8.1.0 and now I'm getting this:

```
Unhandled exception. System.TypeLoadException: Could not load type 'Hangfire.HangfireServiceCollectionExtensions' from assembly 'Hangfire.AspNetCore, Version=1.8.1.0, Culture=neutral, PublicKeyToken=null'.
at Cultiv.Hangfire.HangfireComposer.Compose(IUmbracoBuilder builder)
at Umbraco.Cms.Core.Composing.ComposerGraph.Compose()
at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilderExtensions.AddComposers(IUmbracoBuilder builder)
....
```

Not sure if they moved some stuff around :)

**Comment by nul800sebastiaan** [comment]
@jrunestone I have found the same, I don't know how to fix it yet. Their upgrade instructions mention breaking changes and I've tried many  things already to finalize the upgrade but this one is a blocker I haven't found a solution for when I was trying last week. 
1.7 still works great, so you can just downgrade for now.

There's definitely a few updates I need to make to this package for it to support 1.8!

**Comment by jrunestone** [comment]
@nul800sebastiaan OK thanks for the update!

**Comment by niekvanderreest** [comment]
Hi @nul800sebastiaan,

I recently updated Hangfire to v1.8.1 in an Umbraco 10 project that has an implementation not using Cultiv.Hangfire, my hangfirecomposer has following changes, maybe this is helpfull;

```
builder.Services.AddHangfire(configuration =>
              {
                  configuration
                  .SetDataCompatibilityLevel(CompatibilityLevel.Version_180) // was .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
                  .UseColouredConsoleLogProvider()
                  .UseDashboardMetric(SqlServerStorage.ActiveConnections)
                  .UseDashboardMetric(SqlServerStorage.TotalConnections)
                  .UseConsole()
                  .UseSqlServerStorage(connectionString, new SqlServerStorageOptions
                  {
                      PrepareSchemaIfNecessary = true, // Enabled by default <-- added setting with default value
                      EnableHeavyMigrations = true,     // Disabled by default <-- added setting with NON default setting
                      CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
                      SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
                      QueuePollInterval = TimeSpan.Zero,
                      UseRecommendedIsolationLevel = true,
                      DisableGlobalLocks = true,
                  });
           });
```

Changes are

- .SetDataCompatibilityLevel(CompatibilityLevel.Version_180)
- PrepareSchemaIfNecessary = true, // Enabled by default
- EnableHeavyMigrations = true,     // Disabled by default

**Comment by nul800sebastiaan** [comment]
@niekvanderreest Hi! Sorry I missed your update, this looks promising, I'll have a look and see if I can make it work in the package. I wonder what I was missing, pretty sure I tried all that.

**Comment by AaronSadlerUK** [comment]
@nul800sebastiaan did you get anywhere with this?

I just tried Hangfire 1.8.5 and got the same issue

**Comment by nul800sebastiaan** [comment]
@niekvanderreest @AaronSadlerUK I could have sworn I tried all this before, but it didn't work at the time. Maybe now that the version is 1.8.5 they fixed something but I can't see it from their release notes. So I'll just blame myself then 😂 

v3.0.0 of `Cultiv.Hangfire` is out now: https://github.com/nul800sebastiaan/Cultiv.Hangfire/releases/tag/v3.0.0. As per the release notes, you have to manually update the `Hangfire` NuGet package to v1.8.5 before you can update `Cultiv.Hangfire` to 3.0.0.

**Comment by jrunestone** [comment]
Thanks @nul800sebastiaan, works!
