### ISSUE TITLE
Nuget Dependencies

### ISSUE THREAD

**Issue by cleversolutions** [nul800sebastiaan/Cultiv.Hangfire#2]
Thanks for this package @nul800sebastiaan, I've replaced my implementation with yours on a new u9 site we are building. My implementation didn't have the swanky BackOffice integration 😄. 

Now that 9.0.0 is released, can we updated the dependencies to that? 9.0.0-preview001 is tossing build warnings that it wants me to downgrade to rc001.

**Comment by nul800sebastiaan** [comment]
Good to hear @cleversolutions! v1.0.0 is out now, depending on v9.0.0 final 👍
