### ISSUE TITLE
Support sqlite and/or memory database

### ISSUE THREAD

**Issue by Jogai** [nul800sebastiaan/Cultiv.Hangfire#20]
As a developer it would be nice to be able to run this agains sqlite or inMemory. Some tasks would be fine to just schedule and write to the umbraco log, so for those I think a memory db is enough.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/nul800sebastiaan/Cultiv.Hangfire/commit/98caa8ecdc5ebc0b25b2123a61302a0e893b7471 will be available in v3.1.0

**Comment by nul800sebastiaan** [comment]
I do realize that's it's "all or nothing" right now, so only available if the umbraco db is also SQLite. I plan to make it configurable in the future like enabling the server is configurable now since #18 - happy to look at a PR as well if you want to get it done quicker!

**Comment by Jogai** [comment]
For me this is enough. Thanks!
