### ISSUE TITLE
Startup error on macOS

### ISSUE THREAD

**Issue by ollijonsson** [nul800sebastiaan/Cultiv.Hangfire#24]
Running on macOS (arm64) throws a connection string error at startup:

`Format of the initialization string does not conform to specification starting at index 0.`

- macOS Sonoma 14.1.2 (arm64 processor)
- Umbraco version 12.3.3

Tested on two Macs  - it's a project in active development by multiple people on Windows machines where it works like a charm

Disabling the server **(Hangfire.Server.Disabled)** results in the same error thrown later when **AddAuthorizedUmbracoDashboard** runs

**Comment by nul800sebastiaan** [comment]
Any more error logs than that, it's hard to pinpoint what that error refers to. 

I am assuming you're using v3.1.2 of `Cultiv.Hangfire`?

**Comment by nul800sebastiaan** [comment]
First Google result points to connection strings. Does any of this help? https://stackoverflow.com/questions/8243008/format-of-the-initialization-string-does-not-conform-to-specification-starting-a

**Comment by nul800sebastiaan** [comment]
I haven't heard back so I'll close this for now.
