### ISSUE TITLE
Does this work with multiple instances?

### ISSUE THREAD

**Issue by Yannis-S-Standaert** [nul800sebastiaan/Cultiv.Hangfire#25]
I have a question regarding the support of load balancing / multiple umbraco instances.

I don't see a conditional check to make sure hangfire is only installed on the publisher instance and not on the subscriber instances, does that mean that the same job might run on multiple instances at the same time? Or am I missing something?

**Comment by nul800sebastiaan** [comment]
No! It should only run on 1 server at a time. That's why there's an option to disable the server: https://github.com/nul800sebastiaan/Cultiv.Hangfire/pull/18
