### ISSUE TITLE
How to  create multiple queues to priotize jobs

### ISSUE THREAD

**Issue by firomero** [nul800sebastiaan/Cultiv.Hangfire#27]
Greetings, In found this can be achieved on Hangfire using this docs
https://docs.hangfire.io/en/latest/background-processing/configuring-queues.html

But my question is how to integrate this on Umbraco?

Thank you!

**Comment by nul800sebastiaan** [comment]
Have you tried to just add the code from the documentation? 😅 

I think it should just work.

**Comment by nul800sebastiaan** [comment]
This package doesn't call `UseHangfireServer` so.. that might work! But honestly, I don't know if it will interfere with `UseHangfire`. Do report back!

**Comment by firomero** [comment]
Achieved by using AddHangfire Server with options. Thanks!
