### ISSUE TITLE
Is there a way to add this to a location visible by non-admin users?

### ISSUE THREAD

**Issue by seanrockster** [nul800sebastiaan/Cultiv.Hangfire#33]
We'd like non-admin users to have visibility of the graph, is it possible?

Thanks.

**Comment by nul800sebastiaan** [comment]
No at the moment it's not possible, it's hardcoded to be limited to people with access to the settings section: https://github.com/nul800sebastiaan/Cultiv.Hangfire/blob/main/Cultiv.Hangfire/HangfireComposer.cs#L124C72-L124C93 

You will want to be extremely careful who you give access to the dashboard.. as it has the ability to bring down your whole site quite easily depending on the code in your custom tasks 🙈 😅

**Comment by markadrake** [comment]
We want to expose this to specific users in the Umbraco Backoffice, 
but not expose our settings to those users.

I think it would be great to add some configuration,
to override the default behavior, which should remain the default for obvious reasons, you stated.

Please consider this feature and let us know if you would accept a pull request.

Thank you!

**Comment by nul800sebastiaan** [comment]
I'd love it! I actually think it should be moved to it's own section, then you can just give any user you want access to the section. Should make it easier to choose the correct security level.

Please do note that I haven't been able to make it work on Cloud just yet: https://github.com/nul800sebastiaan/Cultiv.Hangfire/issues/37
