### ISSUE TITLE
Get UmbracoContext and/or Services

### ISSUE THREAD

**Issue by Axendo** [nul800sebastiaan/Cultiv.Hangfire#4]
Hi Sebastiaan,

First of great package! Huge timesaver when it comes to getting Hangfire running in umbraco and configured correctly.
Now i have a working hangfire setup, only it's next to impossible to get services needed to query Umbraco or apply changes (i.e. IContentService)

Have you thought of any way to get servcies injected via DI or get them from IServiceProvider?
I've now "fixed" this issue by modifying Program.cs to add a static reference to my ServiceProvider in the following way.

```
public class Program
{
        public static IServiceProvider _serviceProvider { get; private set; }

        public static void Main(string[] args)
        {
            // this way of building the program adds a static servcieprovider, enabeling getting servcies directly from te servicecollection
            // This is needed in hangfirejobscomposer
            var host = CreateHostBuilder(args).Build();
            _serviceProvider = host.Services;
            host.Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureLogging(x => x.ClearProviders())
                .ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<Startup>());
}
```

Although working, it's not a very nice and pluggable sollution, also I've yet to figure out how to get an UmbracoHelper reference. (have got an UmbracoContextReference working to query cache)

Any idea's on this?

**Comment by nul800sebastiaan** [comment]
@Axendo Sorry for the (very) late reply! I've since blogged about this exact topic here: https://cultiv.nl/blog/using-hangfire-to-update-umbraco-content/
